---
# Site metadata for OpenGraph
name: gh0st.sh
url: https://gh0st.sh
description: |
  A friendly gh0st.

# Global configuration
timezone: America/New_York

# Build Configuration
exclude: ['.envrc','CNAME', 'shell.nix', 'README.md']

# Serve Configuration
host: localhost
port: 8080
...
